#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

RED='\033[0;31m'
NC='\033[0m' # No Color
echo "I ${RED}love${NC} Stack Overflow"

echo 'husky pre-commit hook'
npm run husky:pre-commit:prettier:format
